module.exports = {
    LOGIN_SUCCESS: 'Login successful',
    LOGIN_FAILED: 'Login failed',
    WRONG_PASSWORD: 'Incorrect password',
    CREATED: 'Successfully created',
    TOGGLE_TRACKER: 'Toggle Successfully Tracked',
    FILE_UPLOAD: 'Successfully File Upload.',
    REGISTER_USER: 'You are successfully registered.',
    SEND_OTP: 'Otp has been sent your register number.',
    SEND_OTP_EMAIL: 'Otp has been sent your register email.',
    SUCCESS_OTP: 'Otp Verified',
    FAILED_OTP: 'Invalid Otp.',
    INVALID_USERNAME: 'Invalid username.',
    CREATE_FAILED: 'Failed to create record',
    GET_RECORD_SUCCESS: 'Retrieved records successfully',
    GET_SINGLE_RECORD: 'Retrieved single record successfully',
    UPDATE_SUCCESS: 'Record updated successfully',
    PASSWORD_CHANGES: 'Password has been changed.',
    DELETE_SUCCESS: 'Record deleted successfully',
    NOT_FOUND: 'Record Not Found.',
    NOT_FOUND_FUN: (message) => `${message} does not exist.`,
    ROUTE_NOT_FOUND: 'Route Not Found!',
    EMAIL_NOT_VERIFIED: 'Email must be verified',
    EMAIL_ALREADY_TAKEN: 'Email Already taken',
    BAD_REQUEST: 'Bad request',
    BAD_ROUTINE_ID: 'Invalid routine id',
    BAD_PILLAR_ID: 'Invalid pillar id',
    UNAUTHORIZED: 'Unauthorized access',
    FORBIDDEN: 'Access forbidden',
    PRECONDITION_FAILED: 'Precondition failed',
    TOO_MANY_REQUESTS: 'Too many requests',
    SERVICE_UNAVAILABLE: 'Service unavailable',
    INTERNAL_SERVER_ERROR: 'Internal server error',
    EMAIL_ALREADY_EXISTS: 'The email address is already in use by another account.',
    AUTH_ERRORS: {
        TOKEN_HEADER: 'Token header not found',
        TOKEN: 'Token not found',
        UNAUTHORIZED: 'Oops! Unauthorised access',
        BLOCKED: 'Oops! You are block. Contact to admin.',
    },

    ERROR: {
        LOGIN: {
            USERNAME: 'Incorrect username or password. Please try again',
            WRONG_PASS: 'Password is incorrect. Please try again',
        },
    },
};
